name: atlantis_space
description: Atlantis Space is an isolated space.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.3+4

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  share_plus: ^7.0.2
  url_launcher: ^6.1.11
  fluttertoast: ^8.2.2
  #auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  #change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    #- assets/
    - assets/apks/